In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/building-permit-applications-data/Building_Permits.csv
/kaggle/input/building-permit-applications-data/DataDictionaryBuildingPermit.xlsx
/kaggle/input/nflplaybyplay2009to2016/NFL Play by Play 2009-2017 (v4).csv
/kaggle/input/nflplaybyplay2009to2016/NFL Play by Play 2009-2016 (v3).csv
/kaggle/input/nflplaybyplay2009to2016/NFL Play by Play 2009-2018 (v5).csv

In [2]:
#Reading required building permits data and nfl data

nfl_data = pd.read_csv('/kaggle/input/nflplaybyplay2009to2016/NFL Play by Play 2009-2017 (v4).csv')
building_permits = pd.read_csv('/kaggle/input/building-permit-applications-data/Building_Permits.csv')
building_permits

/tmp/ipykernel_21/1441884491.py:3: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  nfl_data = pd.read_csv('/kaggle/input/nflplaybyplay2009to2016/NFL Play by Play 2009-2017 (v4).csv')
/tmp/ipykernel_21/1441884491.py:4: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  building_permits = pd.read_csv('/kaggle/input/building-permit-applications-data/Building_Permits.csv')

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,NaN,Bush,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,NaN,Indiana,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,NaN,Sutter,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489796283803

In [3]:
#Lets check some data to see what kind of anomalies are there
nfl_data.sample(5)
#AS the output seggests we can see there are lots on NaN feilds with missing data.

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
134626,2012-09-09,2012090900,8,2,1.0,13:40,14,2620.0,38.0,CHI,...,0.0,0.517268,0.482732,0.560391,0.439609,0.517268,0.043122,0.043122,0.0,2012
256038,2014-11-23,2014112312,14,3,2.0,07:33,8,1353.0,42.0,MID,...,NaN,0.801807,0.198193,0.807415,0.192585,0.198193,-0.005607,NaN,NaN,2014
336094,2016-10-27,2016102700,20,4,NaN,02:58,3,178.0,5.0,JAX,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,2016
157574,2012-11-04,2012110410,22,4,NaN,02:45,3,165.0,7.0,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,2012
385759,2017-11-06,2017110600,7,2,NaN,02:47,3,1967.0,0.0,DET,...,NaN,0.120207,0.879793,0.113177,0.886823,0.120207,-0.007031,NaN,NaN,2017

In [4]:
building_permits.sample(5)
#same case for the other data set as well

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
74498,201502027234,8,otc alterations permit,02/02/2015,0822,031,957,NaN,Hayes,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Hayes Valley,94117.0,"(37.77543850944439, -122.43205039806332)",1369685237368
28440,201310189723,3,additions alterations or repairs,10/18/2013,0208,011,706,NaN,Kearny,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Chinatown,94111.0,"(37.79465000612922, -122.4045356807058)",1321396296277
195934,M882547,8,otc alterations permit,01/30/2018,0222,020,1126,NaN,Taylor,St,...,NaN,NaN,NaN,NaN,NaN,3.0,Nob Hill,94108.0,"(37.792930978936404, -122.41247028660328)",1495216233031
11871,201305076345,8,otc alterations permit,05/07/2013,2803,043,1044,NaN,Castro,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Noe Valley,94114.0,"(37.75306846693766, -122.43452793751203)",1304026144635
145215,201612155111,3,additions alterations or repairs,12/15/2016,3533,037,145,NaN,Guerrero,St,...,1.0,constr type 1,1.0,constr type 1,NaN,8.0,Mission,94103.0,"(37.768922887665056, -122.42387435045788)",1447608157035

In [5]:
#lets clean the building_permits datast first
#finding number of missing data peer column
missing_values_count = building_permits.isnull().sum()

print(missing_values_count)

#total missing values
missing_values_count.sum()

Permit Number                                  0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Lot                                            0
Street Number                                  0
Street Number Suffix                      196684
Street Name                                    0
Street Suffix                               2768
Unit                                      169421
Unit Suffix                               196939
Description                                  290
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Issued Date                                14940
Completed Date                            101709
First Construction Document Date           14946
Structural Notification                   191978
Number of Existing Stories                 42784
Number of Proposed Stories                 42868
Voluntary Soft-Story Retrofit             198865
Fire Only Permit                          180073
Permit Expiration Date                     51880
Estimated Cost                             38066
Revised Cost                                6066
Existing Use                               41114
Existing Units                             51538
Proposed Use                               42439
Proposed Units                             50911
Plansets                                   37309
TIDF Compliance                           198898
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Site Permit                               193541
Supervisor District                         1717
Neighborhoods - Analysis Boundaries         1725
Zipcode                                     1716
Location                                    1700
Record ID                                      0
dtype: int64

2245941

In [6]:
#lets try removing the nan's directly and check whats left

building_permits.dropna()

#since each row had at least one NaN value all the data was removed. so this wont work. Trying alternatives

Empty DataFrame
Columns: [Permit Number, Permit Type, Permit Type Definition, Permit Creation Date, Block, Lot, Street Number, Street Number Suffix, Street Name, Street Suffix, Unit, Unit Suffix, Description, Current Status, Current Status Date, Filed Date, Issued Date, Completed Date, First Construction Document Date, Structural Notification, Number of Existing Stories, Number of Proposed Stories, Voluntary Soft-Story Retrofit, Fire Only Permit, Permit Expiration Date, Estimated Cost, Revised Cost, Existing Use, Existing Units, Proposed Use, Proposed Units, Plansets, TIDF Compliance, Existing Construction Type, Existing Construction Type Description, Proposed Construction Type, Proposed Construction Type Description, Site Permit, Supervisor District, Neighborhoods - Analysis Boundaries, Zipcode, Location, Record ID]
Index: []

[0 rows x 43 columns]

In [7]:
#lets try removing columns with NaNs instead
columns_with_nan_dropped = building_permits.dropna(axis = 1)
columns_with_nan_dropped.head()

#here we can see there are data left. But still we removed much more data , which may be important data

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Current Status,Current Status Date,Filed Date,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,Ellis,expired,12/21/2017,05/06/2015,1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,Geary,issued,08/03/2017,04/19/2016,1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,withdrawn,09/26/2017,05/27/2016,1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,complete,07/24/2017,11/07/2016,1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,Market,issued,12/01/2017,11/28/2016,144548169992

In [8]:
#lets check how much data was lost
print(f"Original columns = {building_permits.shape[1]} ")
print(f"Dropped columns = {columns_with_nan_dropped.shape[1]} ")

#At this point even if we lost some data , our dataset in hand have no NaN's

Original columns = 43
Dropped columns = 12