In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/nflplaybyplay2009to2016/NFL Play by Play 2009-2017 (v4).csv
/kaggle/input/nflplaybyplay2009to2016/NFL Play by Play 2009-2016 (v3).csv
/kaggle/input/nflplaybyplay2009to2016/NFL Play by Play 2009-2018 (v5).csv
/kaggle/input/building-permit-applications-data/Building_Permits.csv
/kaggle/input/building-permit-applications-data/DataDictionaryBuildingPermit.xlsx
/kaggle/input/kickstarter-projects/ks-projects-201801.csv
/kaggle/input/kickstarter-projects/ks-projects-201612.csv

In [2]:
#Reading required building permits data and nfl data

nfl_data = pd.read_csv('/kaggle/input/nflplaybyplay2009to2016/NFL Play by Play 2009-2017 (v4).csv')
building_permits = pd.read_csv('/kaggle/input/building-permit-applications-data/Building_Permits.csv')
building_permits

/tmp/ipykernel_20/1441884491.py:3: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  nfl_data = pd.read_csv('/kaggle/input/nflplaybyplay2009to2016/NFL Play by Play 2009-2017 (v4).csv')
/tmp/ipykernel_20/1441884491.py:4: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  building_permits = pd.read_csv('/kaggle/input/building-permit-applications-data/Building_Permits.csv')

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,NaN,Bush,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,NaN,Indiana,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,NaN,Sutter,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489796283803

In [3]:
#Lets check some data to see what kind of anomalies are there
nfl_data.sample(5)
#AS the output seggests we can see there are lots on NaN feilds with missing data.

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
290974,2015-11-01,2015110101,5,2,NaN,13:52,14,2632.0,35.0,BAL,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,2015
284452,2015-10-12,2015101200,19,4,4.0,14:52,15,892.0,4.0,PIT,...,NaN,0.482048,0.517952,0.541277,0.458723,0.482048,0.059229,NaN,NaN,2015
122778,2011-12-04,2011120406,4,1,2.0,04:41,5,2981.0,0.0,DET,...,NaN,0.615258,0.384742,0.616499,0.383501,0.384742,-0.001241,NaN,NaN,2011
54968,2010-10-03,2010100311,20,4,2.0,03:53,4,233.0,45.0,SD,...,0.00535,0.999955,0.000045,0.999971,0.000029,0.000045,-0.000016,-0.000016,5.739142e-07,2010
298230,2015-11-22,2015112203,5,2,1.0,11:47,12,2507.0,33.0,NYJ,...,NaN,0.683570,0.316430,0.669728,0.330272,0.683570,-0.013842,NaN,NaN,2015

In [4]:
building_permits.sample(5)
#same case for the other data set as well

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
86955,201505277324,8,otc alterations permit,05/27/2015,1221,003,123,NaN,Lyon,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Haight Ashbury,94117.0,"(37.77218538901177, -122.44260508940698)",138297192840
82497,201504153678,8,otc alterations permit,04/15/2015,3532,009,1754,NaN,Mission,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Mission,94103.0,"(37.768988373367115, -122.42034656041355)",1378159496275
141600,M736148,8,otc alterations permit,11/03/2016,0184,036,1333,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,NaN,3.0,Russian Hill,94109.0,"(37.795262786688355, -122.41717919967991)",1443190295458
36315,201401146225,8,otc alterations permit,01/14/2014,3724,071,155,NaN,05th,St,...,1.0,constr type 1,1.0,constr type 1,NaN,6.0,South of Market,94103.0,"(37.78239342903023, -122.4052137928674)",1329685458119
185183,201710060613,8,otc alterations permit,10/06/2017,0218,015,1590,NaN,Sacramento,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79190333210937, -122.41894307732841)",1482481232935

In [5]:
#lets clean the building_permits datast first
#finding number of missing data peer column
missing_values_count = building_permits.isnull().sum()

print(missing_values_count)

#total missing values
missing_values_count.sum()

Permit Number                                  0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Lot                                            0
Street Number                                  0
Street Number Suffix                      196684
Street Name                                    0
Street Suffix                               2768
Unit                                      169421
Unit Suffix                               196939
Description                                  290
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Issued Date                                14940
Completed Date                            101709
First Construction Document Date           14946
Structural Notification                   191978
Number of Existing Stories                 42784
Number of Proposed Stories                 42868
Voluntary Soft-Story Retrofit             198865
Fire Only Permit                          180073
Permit Expiration Date                     51880
Estimated Cost                             38066
Revised Cost                                6066
Existing Use                               41114
Existing Units                             51538
Proposed Use                               42439
Proposed Units                             50911
Plansets                                   37309
TIDF Compliance                           198898
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Site Permit                               193541
Supervisor District                         1717
Neighborhoods - Analysis Boundaries         1725
Zipcode                                     1716
Location                                    1700
Record ID                                      0
dtype: int64

2245941

In [6]:
#lets try removing the nan's directly and check whats left

building_permits.dropna()

#since each row had at least one NaN value all the data was removed. so this wont work. Trying alternatives

Empty DataFrame
Columns: [Permit Number, Permit Type, Permit Type Definition, Permit Creation Date, Block, Lot, Street Number, Street Number Suffix, Street Name, Street Suffix, Unit, Unit Suffix, Description, Current Status, Current Status Date, Filed Date, Issued Date, Completed Date, First Construction Document Date, Structural Notification, Number of Existing Stories, Number of Proposed Stories, Voluntary Soft-Story Retrofit, Fire Only Permit, Permit Expiration Date, Estimated Cost, Revised Cost, Existing Use, Existing Units, Proposed Use, Proposed Units, Plansets, TIDF Compliance, Existing Construction Type, Existing Construction Type Description, Proposed Construction Type, Proposed Construction Type Description, Site Permit, Supervisor District, Neighborhoods - Analysis Boundaries, Zipcode, Location, Record ID]
Index: []

[0 rows x 43 columns]

In [7]:
#lets try removing columns with NaNs instead
columns_with_nan_dropped = building_permits.dropna(axis = 1)
columns_with_nan_dropped.head()

#here we can see there are data left. But still we removed much more data , which may be important data

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Current Status,Current Status Date,Filed Date,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,Ellis,expired,12/21/2017,05/06/2015,1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,Geary,issued,08/03/2017,04/19/2016,1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,withdrawn,09/26/2017,05/27/2016,1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,complete,07/24/2017,11/07/2016,1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,Market,issued,12/01/2017,11/28/2016,144548169992

In [8]:
#lets check how much data was lost
print(f"Original columns = {building_permits.shape[1]} ")
print(f"Dropped columns = {columns_with_nan_dropped.shape[1]} ")

#At this point even if we lost some data , our dataset in hand have no NaN's

Original columns = 43
Dropped columns = 12

In [9]:
#Another option than dropping the columns could be adding the missing values automatically
#lets take a small subset and try that

subset_data = building_permits.loc[:,'Street Number Suffix':'Issued Date']
subset_data.head()

,Street Number Suffix,Street Name,Street Suffix,Unit,Unit Suffix,Description,Current Status,Current Status Date,Filed Date,Issued Date
0,NaN,Ellis,St,NaN,NaN,"ground fl facade: to erect illuminated, electr...",expired,12/21/2017,05/06/2015,11/09/2015
1,NaN,Geary,St,0.0,NaN,remove (e) awning and associated signs.,issued,08/03/2017,04/19/2016,08/03/2017
2,NaN,Pacific,Av,NaN,NaN,installation of separating wall,withdrawn,09/26/2017,05/27/2016,NaN
3,NaN,Pacific,Av,0.0,NaN,repair dryrot & stucco at front of bldg.,complete,07/24/2017,11/07/2016,07/18/2017
4,NaN,Market,St,NaN,NaN,demolish retail/office/commercial 3-story buil...,issued,12/01/2017,11/28/2016,12/01/2017

In [10]:
#using pandas to fill Na's with 0(This could be an alternative)
subset_data.fillna(0)

,Street Number Suffix,Street Name,Street Suffix,Unit,Unit Suffix,Description,Current Status,Current Status Date,Filed Date,Issued Date
0,0,Ellis,St,0.0,0,"ground fl facade: to erect illuminated, electr...",expired,12/21/2017,05/06/2015,11/09/2015
1,0,Geary,St,0.0,0,remove (e) awning and associated signs.,issued,08/03/2017,04/19/2016,08/03/2017
2,0,Pacific,Av,0.0,0,installation of separating wall,withdrawn,09/26/2017,05/27/2016,0
3,0,Pacific,Av,0.0,0,repair dryrot & stucco at front of bldg.,complete,07/24/2017,11/07/2016,07/18/2017
4,0,Market,St,0.0,0,demolish retail/office/commercial 3-story buil...,issued,12/01/2017,11/28/2016,12/01/2017
...,...,...,...,...,...,...,...,...,...,...
198895,0,Montgomery,St,0.0,0,street space,issued,12/05/2017,12/05/2017,12/05/2017
198896,0,Bush,St,0.0,0,fire alarm upgrade ref 201704123852,issued,12/06/2017,12/05/2017,12/06/2017
198897,0,Indiana,St,0.0,0,street space,issued,12/06/2017,12/06/2017,12/06/2017
198898,0,Sutter,St,0.0,0,street space permit,issued,12/06/2017,12/06/2017,12/06/2017
198899,0,Pacific,Av,0.0,0,street space permit,issued,12/07/2017,12/07/2017,12/07/2017

In [11]:
#or we can try filling Na's with the value that comes right after it in the same column
#then replace remaining na,s with 0
subset_data.fillna(method = 'bfill',axis = 0).fillna(0)

#This method is useful if there is a logical order in the data that makes some sense

,Street Number Suffix,Street Name,Street Suffix,Unit,Unit Suffix,Description,Current Status,Current Status Date,Filed Date,Issued Date
0,A,Ellis,St,0.0,A,"ground fl facade: to erect illuminated, electr...",expired,12/21/2017,05/06/2015,11/09/2015
1,A,Geary,St,0.0,A,remove (e) awning and associated signs.,issued,08/03/2017,04/19/2016,08/03/2017
2,A,Pacific,Av,0.0,A,installation of separating wall,withdrawn,09/26/2017,05/27/2016,07/18/2017
3,A,Pacific,Av,0.0,A,repair dryrot & stucco at front of bldg.,complete,07/24/2017,11/07/2016,07/18/2017
4,A,Market,St,0.0,A,demolish retail/office/commercial 3-story buil...,issued,12/01/2017,11/28/2016,12/01/2017
...,...,...,...,...,...,...,...,...,...,...
198895,0,Montgomery,St,0.0,0,street space,issued,12/05/2017,12/05/2017,12/05/2017
198896,0,Bush,St,0.0,0,fire alarm upgrade ref 201704123852,issued,12/06/2017,12/05/2017,12/06/2017
198897,0,Indiana,St,0.0,0,street space,issued,12/06/2017,12/06/2017,12/06/2017
198898,0,Sutter,St,0.0,0,street space permit,issued,12/06/2017,12/06/2017,12/06/2017
198899,0,Pacific,Av,0.0,0,street space permit,issued,12/07/2017,12/07/2017,12/07/2017

In [12]:
#Scale and normalize Data

#step 1 : Setting the environment

#loading required modules
import numpy as np

#FOR transformation
from scipy import stats

#plotting modules
import seaborn as sns
import matplotlib.pyplot as plt


#Reading required data: For this task we will use the kickstarter-projects data for 2018
data = pd.read_csv('/kaggle/input/kickstarter-projects/ks-projects-201801.csv')
data.head()

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00